<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrderCount', 'doctrine');

/**
 * BaseOrderCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $action
 * @property integer $order_count
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getAction()      Returns the current record's "action" value
 * @method integer    getOrderCount()  Returns the current record's "order_count" value
 * @method OrderCount setId()          Sets the current record's "id" value
 * @method OrderCount setAction()      Sets the current record's "action" value
 * @method OrderCount setOrderCount()  Sets the current record's "order_count" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_count');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('action', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('order_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}