<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Classroom', 'doctrine');

/**
 * BaseClassroom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $creator
 * @property string $title
 * @property string $textarea
 * @property string $post_date
 * @property string $other_dates
 * @property integer $views
 * @property integer $reply_post
 * @property string $topic
 * @property string $parent_id
 * @property string $group_id
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getCreator()     Returns the current record's "creator" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getTextarea()    Returns the current record's "textarea" value
 * @method string    getPostDate()    Returns the current record's "post_date" value
 * @method string    getOtherDates()  Returns the current record's "other_dates" value
 * @method integer   getViews()       Returns the current record's "views" value
 * @method integer   getReplyPost()   Returns the current record's "reply_post" value
 * @method string    getTopic()       Returns the current record's "topic" value
 * @method string    getParentId()    Returns the current record's "parent_id" value
 * @method string    getGroupId()     Returns the current record's "group_id" value
 * @method Classroom setId()          Sets the current record's "id" value
 * @method Classroom setCreator()     Sets the current record's "creator" value
 * @method Classroom setTitle()       Sets the current record's "title" value
 * @method Classroom setTextarea()    Sets the current record's "textarea" value
 * @method Classroom setPostDate()    Sets the current record's "post_date" value
 * @method Classroom setOtherDates()  Sets the current record's "other_dates" value
 * @method Classroom setViews()       Sets the current record's "views" value
 * @method Classroom setReplyPost()   Sets the current record's "reply_post" value
 * @method Classroom setTopic()       Sets the current record's "topic" value
 * @method Classroom setParentId()    Sets the current record's "parent_id" value
 * @method Classroom setGroupId()     Sets the current record's "group_id" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassroom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classroom');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 3,
             ));
        $this->hasColumn('creator', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('textarea', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_date', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('other_dates', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('views', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('reply_post', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('topic', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('parent_id', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('group_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}