<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtAnalysisMedalDetails', 'doctrine');

/**
 * BaseSbtAnalysisMedalDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $analysis_id
 * @property integer $analysis_medal_type_id
 * @property string $award_note_by_admin
 * @property integer $awarded_by
 * @property timestamp $created_at
 * 
 * @method integer                 getId()                     Returns the current record's "id" value
 * @method integer                 getAnalysisId()             Returns the current record's "analysis_id" value
 * @method integer                 getAnalysisMedalTypeId()    Returns the current record's "analysis_medal_type_id" value
 * @method string                  getAwardNoteByAdmin()       Returns the current record's "award_note_by_admin" value
 * @method integer                 getAwardedBy()              Returns the current record's "awarded_by" value
 * @method timestamp               getCreatedAt()              Returns the current record's "created_at" value
 * @method SbtAnalysisMedalDetails setId()                     Sets the current record's "id" value
 * @method SbtAnalysisMedalDetails setAnalysisId()             Sets the current record's "analysis_id" value
 * @method SbtAnalysisMedalDetails setAnalysisMedalTypeId()    Sets the current record's "analysis_medal_type_id" value
 * @method SbtAnalysisMedalDetails setAwardNoteByAdmin()       Sets the current record's "award_note_by_admin" value
 * @method SbtAnalysisMedalDetails setAwardedBy()              Sets the current record's "awarded_by" value
 * @method SbtAnalysisMedalDetails setCreatedAt()              Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtAnalysisMedalDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_analysis_medal_details');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('analysis_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('analysis_medal_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('award_note_by_admin', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('awarded_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}