<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArticleCategory', 'doctrine');

/**
 * BaseArticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $category_name
 * @property string $category_icon
 * @property Doctrine_Collection $Article
 * 
 * @method integer             getCategoryId()    Returns the current record's "category_id" value
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method string              getCategoryIcon()  Returns the current record's "category_icon" value
 * @method Doctrine_Collection getArticle()       Returns the current record's "Article" collection
 * @method ArticleCategory     setCategoryId()    Sets the current record's "category_id" value
 * @method ArticleCategory     setCategoryName()  Sets the current record's "category_name" value
 * @method ArticleCategory     setCategoryIcon()  Sets the current record's "category_icon" value
 * @method ArticleCategory     setArticle()       Sets the current record's "Article" collection
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_category');
        $this->hasColumn('category_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('category_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('category_icon', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article', array(
             'local' => 'category_id',
             'foreign' => 'category_id'));
    }
}