<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtCombinedAnalysisData', 'doctrine');

/**
 * BaseSbtCombinedAnalysisData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $analysis_id
 * @property string $combined_usernames
 * @property timestamp $created_at
 * 
 * @method integer                 getId()                 Returns the current record's "id" value
 * @method integer                 getAnalysisId()         Returns the current record's "analysis_id" value
 * @method string                  getCombinedUsernames()  Returns the current record's "combined_usernames" value
 * @method timestamp               getCreatedAt()          Returns the current record's "created_at" value
 * @method SbtCombinedAnalysisData setId()                 Sets the current record's "id" value
 * @method SbtCombinedAnalysisData setAnalysisId()         Sets the current record's "analysis_id" value
 * @method SbtCombinedAnalysisData setCombinedUsernames()  Sets the current record's "combined_usernames" value
 * @method SbtCombinedAnalysisData setCreatedAt()          Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtCombinedAnalysisData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_combined_analysis_data');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('analysis_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('combined_usernames', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}