<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtStockList', 'doctrine');

/**
 * BaseSbtStockList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $stock_name
 * @property integer $display_order
 * @property Doctrine_Collection $SbtObject
 * @property Doctrine_Collection $SbtStocklistSector
 * @property Doctrine_Collection $SbtMarketStocklist
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getStockName()          Returns the current record's "stock_name" value
 * @method integer             getDisplayOrder()       Returns the current record's "display_order" value
 * @method Doctrine_Collection getSbtObject()          Returns the current record's "SbtObject" collection
 * @method Doctrine_Collection getSbtStocklistSector() Returns the current record's "SbtStocklistSector" collection
 * @method Doctrine_Collection getSbtMarketStocklist() Returns the current record's "SbtMarketStocklist" collection
 * @method SbtStockList        setId()                 Sets the current record's "id" value
 * @method SbtStockList        setStockName()          Sets the current record's "stock_name" value
 * @method SbtStockList        setDisplayOrder()       Sets the current record's "display_order" value
 * @method SbtStockList        setSbtObject()          Sets the current record's "SbtObject" collection
 * @method SbtStockList        setSbtStocklistSector() Sets the current record's "SbtStocklistSector" collection
 * @method SbtStockList        setSbtMarketStocklist() Sets the current record's "SbtMarketStocklist" collection
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtStockList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_stock_list');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('stock_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('display_order', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SbtObject', array(
             'local' => 'id',
             'foreign' => 'stocklist_id'));

        $this->hasMany('SbtStocklistSector', array(
             'local' => 'id',
             'foreign' => 'sbt_stocklist_id'));

        $this->hasMany('SbtMarketStocklist', array(
             'local' => 'id',
             'foreign' => 'sbt_stocklist_id'));
    }
}