<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtchartType', 'doctrine');

/**
 * BaseBtchartType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $chart_type_category
 * @property string $chart_type_name
 * @property string $chart_type_text
 * @property string $chart_type_short_name
 * @property string $chart_type_image
 * @property string $chart_type_file
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer     getId()                    Returns the current record's "id" value
 * @method string      getChartTypeCategory()     Returns the current record's "chart_type_category" value
 * @method string      getChartTypeName()         Returns the current record's "chart_type_name" value
 * @method string      getChartTypeText()         Returns the current record's "chart_type_text" value
 * @method string      getChartTypeShortName()    Returns the current record's "chart_type_short_name" value
 * @method string      getChartTypeImage()        Returns the current record's "chart_type_image" value
 * @method string      getChartTypeFile()         Returns the current record's "chart_type_file" value
 * @method timestamp   getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()             Returns the current record's "updated_at" value
 * @method BtchartType setId()                    Sets the current record's "id" value
 * @method BtchartType setChartTypeCategory()     Sets the current record's "chart_type_category" value
 * @method BtchartType setChartTypeName()         Sets the current record's "chart_type_name" value
 * @method BtchartType setChartTypeText()         Sets the current record's "chart_type_text" value
 * @method BtchartType setChartTypeShortName()    Sets the current record's "chart_type_short_name" value
 * @method BtchartType setChartTypeImage()        Sets the current record's "chart_type_image" value
 * @method BtchartType setChartTypeFile()         Sets the current record's "chart_type_file" value
 * @method BtchartType setCreatedAt()             Sets the current record's "created_at" value
 * @method BtchartType setUpdatedAt()             Sets the current record's "updated_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtchartType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btchart_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('chart_type_category', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chart_type_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chart_type_text', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chart_type_short_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chart_type_image', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('chart_type_file', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}