<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtchartFavorite', 'doctrine');

/**
 * BaseBtchartFavorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $stock_id
 * @property integer $stock_type
 * @property integer $chart_type
 * @property string $description
 * @property timestamp $created_at
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getUserId()      Returns the current record's "user_id" value
 * @method integer         getStockId()     Returns the current record's "stock_id" value
 * @method integer         getStockType()   Returns the current record's "stock_type" value
 * @method integer         getChartType()   Returns the current record's "chart_type" value
 * @method string          getDescription() Returns the current record's "description" value
 * @method timestamp       getCreatedAt()   Returns the current record's "created_at" value
 * @method BtchartFavorite setId()          Sets the current record's "id" value
 * @method BtchartFavorite setUserId()      Sets the current record's "user_id" value
 * @method BtchartFavorite setStockId()     Sets the current record's "stock_id" value
 * @method BtchartFavorite setStockType()   Sets the current record's "stock_type" value
 * @method BtchartFavorite setChartType()   Sets the current record's "chart_type" value
 * @method BtchartFavorite setDescription() Sets the current record's "description" value
 * @method BtchartFavorite setCreatedAt()   Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtchartFavorite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btchart_favorite');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('stock_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('stock_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('chart_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}