<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Moderatebatch', 'doctrine');

/**
 * BaseModeratebatch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $currentcnt
 * @property string $currentmails
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property integer $process_status
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method integer       getCurrentcnt()     Returns the current record's "currentcnt" value
 * @method string        getCurrentmails()   Returns the current record's "currentmails" value
 * @method timestamp     getStartTime()      Returns the current record's "start_time" value
 * @method timestamp     getEndTime()        Returns the current record's "end_time" value
 * @method integer       getProcessStatus()  Returns the current record's "process_status" value
 * @method Moderatebatch setId()             Sets the current record's "id" value
 * @method Moderatebatch setCurrentcnt()     Sets the current record's "currentcnt" value
 * @method Moderatebatch setCurrentmails()   Sets the current record's "currentmails" value
 * @method Moderatebatch setStartTime()      Sets the current record's "start_time" value
 * @method Moderatebatch setEndTime()        Sets the current record's "end_time" value
 * @method Moderatebatch setProcessStatus()  Sets the current record's "process_status" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModeratebatch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('moderatebatch');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('currentcnt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('currentmails', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('start_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('process_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}