<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtPublisherRequest', 'doctrine');

/**
 * BaseSbtPublisherRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $author_id
 * @property integer $request_status
 * @property timestamp $created_at
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getAuthorId()       Returns the current record's "author_id" value
 * @method integer             getRequestStatus()  Returns the current record's "request_status" value
 * @method timestamp           getCreatedAt()      Returns the current record's "created_at" value
 * @method sfGuardUser         getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method SbtPublisherRequest setId()             Sets the current record's "id" value
 * @method SbtPublisherRequest setAuthorId()       Sets the current record's "author_id" value
 * @method SbtPublisherRequest setRequestStatus()  Sets the current record's "request_status" value
 * @method SbtPublisherRequest setCreatedAt()      Sets the current record's "created_at" value
 * @method SbtPublisherRequest setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtPublisherRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_publisher_request');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('author_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('request_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'author_id',
             'foreign' => 'id'));
    }
}