<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BorstArticleComment', 'doctrine');

/**
 * BaseBorstArticleComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $article_comment
 * @property string $subject
 * @property integer $article_id
 * @property integer $comment_by
 * @property timestamp $created_at
 * @property Article $Article
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getArticleComment()  Returns the current record's "article_comment" value
 * @method string              getSubject()         Returns the current record's "subject" value
 * @method integer             getArticleId()       Returns the current record's "article_id" value
 * @method integer             getCommentBy()       Returns the current record's "comment_by" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method Article             getArticle()         Returns the current record's "Article" value
 * @method BorstArticleComment setId()              Sets the current record's "id" value
 * @method BorstArticleComment setArticleComment()  Sets the current record's "article_comment" value
 * @method BorstArticleComment setSubject()         Sets the current record's "subject" value
 * @method BorstArticleComment setArticleId()       Sets the current record's "article_id" value
 * @method BorstArticleComment setCommentBy()       Sets the current record's "comment_by" value
 * @method BorstArticleComment setCreatedAt()       Sets the current record's "created_at" value
 * @method BorstArticleComment setArticle()         Sets the current record's "Article" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBorstArticleComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('borst_article_comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('article_comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('subject', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comment_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'article_id'));
    }
}