<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NewsLetter', 'doctrine');

/**
 * BaseNewsLetter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $ads
 * @property string $article
 * @property string $sbt_article
 * @property string $blog
 * @property boolean $publish
 * @property boolean $sent
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getName()        Returns the current record's "name" value
 * @method string     getAds()         Returns the current record's "ads" value
 * @method string     getArticle()     Returns the current record's "article" value
 * @method string     getSbtArticle()  Returns the current record's "sbt_article" value
 * @method string     getBlog()        Returns the current record's "blog" value
 * @method boolean    getPublish()     Returns the current record's "publish" value
 * @method boolean    getSent()        Returns the current record's "sent" value
 * @method NewsLetter setId()          Sets the current record's "id" value
 * @method NewsLetter setName()        Sets the current record's "name" value
 * @method NewsLetter setAds()         Sets the current record's "ads" value
 * @method NewsLetter setArticle()     Sets the current record's "article" value
 * @method NewsLetter setSbtArticle()  Sets the current record's "sbt_article" value
 * @method NewsLetter setBlog()        Sets the current record's "blog" value
 * @method NewsLetter setPublish()     Sets the current record's "publish" value
 * @method NewsLetter setSent()        Sets the current record's "sent" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsLetter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_letter');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('ads', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('article', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('sbt_article', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('blog', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('publish', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('sent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}