<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtAnalysisComment', 'doctrine');

/**
 * BaseSbtAnalysisComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $analysis_comment
 * @property string $subject
 * @property integer $analysis_id
 * @property integer $comment_by
 * @property timestamp $created_at
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method string             getAnalysisComment()  Returns the current record's "analysis_comment" value
 * @method string             getSubject()          Returns the current record's "subject" value
 * @method integer            getAnalysisId()       Returns the current record's "analysis_id" value
 * @method integer            getCommentBy()        Returns the current record's "comment_by" value
 * @method timestamp          getCreatedAt()        Returns the current record's "created_at" value
 * @method SbtAnalysisComment setId()               Sets the current record's "id" value
 * @method SbtAnalysisComment setAnalysisComment()  Sets the current record's "analysis_comment" value
 * @method SbtAnalysisComment setSubject()          Sets the current record's "subject" value
 * @method SbtAnalysisComment setAnalysisId()       Sets the current record's "analysis_id" value
 * @method SbtAnalysisComment setCommentBy()        Sets the current record's "comment_by" value
 * @method SbtAnalysisComment setCreatedAt()        Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtAnalysisComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_analysis_comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('analysis_comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('subject', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('analysis_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comment_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}