<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NewsletterPublic', 'doctrine');

/**
 * BaseNewsletterPublic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * 
 * @method integer          getId()    Returns the current record's "id" value
 * @method string           getEmail() Returns the current record's "email" value
 * @method NewsletterPublic setId()    Sets the current record's "id" value
 * @method NewsletterPublic setEmail() Sets the current record's "email" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletterPublic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_public');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}