# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  system_culture: en,es
  mail_sender_email: btshop@borstjanaren.se
  mail_reply_email: btshop@borstjanaren.se
  mail_shop_email: btshop@borstjanaren.se
  host_name: www.borstjanaren.se
  newsletter_email: ej_svarsadress@borstjanaren.se