# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: spool
      spool_class:       Swift_FileSpool
      spool_arguments: 
        path: /var/www/vhosts/borstjanaren.se/httpdocs/spool
      #spool_arguments:   ["D:/borst/spool"]	  
#     delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          #host:        213.180.95.199
          host:       email-smtp.eu-west-1.amazonaws.com
          port:       465
          encryption: ssl
          username: AKIAINAMNI2SII45J6UQ  
          password: Alngsbd4/xC4WM41Z0Ka/XBveQmsfR17FnNpRf180u7Q
          #username:  henrik.hallenborg
          #password:  Ben4President
          #username:   matjare@thephpprojects.com
          #password:   Matjare456

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

  transport:
    class: Swift_SmtpTransport
    param:
          host:       localhost
          port:       25
          encryption: ~
          username: btshop@borstjanaren.se  
          password: Kvtyw63945#
      #username:   matjare@thephpprojects.com
      #password:   Matjare456

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       localhost
          port:       25
          encryption: ~
          username: btshop@borstjanaren.se  
          password: Kvtyw63945#

  user:
    class: myUser
    param:
      timeout: 43200		  