<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/07/31 08:22:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
