<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/08/01 06:19:29
sfConfig::add(array(
  'mod_isicsbreadcrumbs_enabled' => true,
  'mod_isicsbreadcrumbs_view_class' => 'sfPHP',
));
