<?php

/**
 * ArticleHtml
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleHtml extends BaseArticleHtml
{
	/*
	*
	* This function returns selected record.
	*
	*/
	
	public function getSelectedHtmlRecord($index) 
	{ 
		$selected_record_cri = Doctrine_Query::create()
	   					      ->from('ArticleHtml ah')
						      ->where('ah.article_id = ?', $index);

		$selected_record_data = $selected_record_cri->fetchOne();
		return $selected_record_data;
	}
	
	/*
	*
	* This function updates a perticular record.
	*
	*/
	
	public function updateSelectedHtmlRecord($html_file_path) 
	{ 
		$this->html_file_path = $html_file_path;
		$this->save();
	}
	
	/*
	*
	* This function inserts new record.
	*
	*/
	
	public function insertNewHtmlRecord($article_id,$html_file_path,$created_at) 
	{ 
		$this->article_id = $article_id;
		$this->html_file_path = $html_file_path;
		$this->created_at = $created_at;
		$this->save();
	}
}