<?php

/**
 * ArticleType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleType extends BaseArticleType
{
	/*
	*
	* This function returns selected article type.
	*
	*/
	
	public function getSelectedArticleType($index) 
	{ 
		$selected_article_type_cri = Doctrine_Query::create()
	   					      		   ->from('ArticleType at')
						               ->where('at.type_id = ?', $index);

		$selected_article_type_data = $selected_article_type_cri->fetchOne();
		return $selected_article_type_data;
	}
	
	/*
	*
	* This function saves article type name.
	*
	*/
	
	public function setArticleTypeName($name)
	{ 
		$this->type_name = $name;
		$this->save();
	}
	
	/*
	*
	* This function addes new article type name.
	*
	*/
	
	public function addNewArticleTypeName($name)
	{ 
		$this->type_name = $name;
		$this->save();
	}
	
	/*
	*
	* This function returns 1 find type exsist, else 0.
	*
	*/
	
	public function isTypePresent($type_name) 
	{ 
		$find_article_type_cri = Doctrine_Query::create()
	   					      		   ->from('ArticleType at')
						               ->where('at.type_name = ?', $type_name);

		$find_article_type_data = $find_article_type_cri->fetchOne();
		return $find_article_type_data ? 1 : 0;
	}
}