<?php

/**
 * BtShopPriceDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtShopPriceDetails extends BaseBtShopPriceDetails
{

   /*
	*
	* This function searches for all records of perticular article.
	*
	*/
	public function searchShopArticles($id)
    {
		$query = Doctrine_Query::create()->from('BtShopPriceDetails bspd')->where('bspd.btshop_article_id = ? ', $id);
		$data =  $query->execute();	
		return $data;	
	}

   /*
	*
	* This function searches and deletes records of perticular article.
	*
	*/
	public function searchAndDelete($id)
    {
		$query = Doctrine_Query::create()->from('BtShopPriceDetails bspd')->where('bspd.btshop_article_id = ? ', $id);
		$data =  $query->execute();
		
		foreach($data as $rec)
		{
			$rec->delete();
		}
	}

   /*
	*
	* This function updates article price.
	*
	*/
	public function updateSelectedPrice($id,$arr)
	{ 
		$this->searchAndDelete($id);
		
		foreach ($arr['shop_qty'] as $key => $value)
		{
			$price_dtl = new BtShopPriceDetails();
			
			$price_dtl->btshop_article_id = $id;
			$price_dtl->btshop_product_quantity = $arr['shop_qty'][$key];
			$price_dtl->btshop_price_unit_id = $arr["quantity_unit"][$key];
			$price_dtl->btshop_product_price = $arr["shop_product_price"][$key];
			$price_dtl->btshop_product_text = $arr["shop_product_text"][$key];
			$price_dtl->created_at = date("Y-m-d H:i:s");
			$price_dtl->save();
			//echo $arr['shop_qty'][$key].' = '.$arr["shop_product_price"][$key].' = '.$arr["shop_product_text"][$key].'<br/>';
		}
		
	}
	
   /*
	*
	* This function searches records of perticular article.
	*
	*/
	public function getSearchRecord($id)
    {
		$query = Doctrine_Query::create()->from('BtShopPriceDetails bspd')->where('bspd.id = ? ', $id);
		$data =  $query->fetchOne();
		return $data;
	}
    
   /*
	*
	* This function returns the Min/Max price of particular article depedning on order specified.
	*
	*/
    public static function getMinPriceOfArticle($article_id,$order='DESC')
    {
        $order = 'ASC';
        $query = Doctrine_Query::create()->select('bspd.btshop_product_price')->from('BtShopPriceDetails bspd')->where('bspd.btshop_article_id = ? ', $article_id)->orderBy('bspd.btshop_product_price '.$order);
		$data =  $query->fetchOne();
		return $data->btshop_product_price;        
    }

}