<?php

/**
 * NewsletterSent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NewsletterSent extends BaseNewsletterSent
{
	public function addSentMail($number_sent,$data) 
	{
		$this->date = date("Y-m-d");
		$this->recipiants = $number_sent;
		$this->kundgrupp = $data['kundgrupp'];
		$this->subject = $data['subject'];
		$this->body = $data['mail_body'];
		$this->save();
	}
	
	public function getAllSentMailData() 
	{
		$query = Doctrine_Query::create()->from('NewsletterSent ns')->orderBy('ns.date DESC');
		return $query;
	}
}