<?php

/**
 * SbtCombinedAnalysisData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtCombinedAnalysisData extends BaseSbtCombinedAnalysisData
{

	/*
	*
	* This function searches for already existing image of user.
	*
	*/
	public function searchPreviousRecord($id) 
	{
		$query = Doctrine_Query::create()
	   					      ->from('SbtCombinedAnalysisData scd')
						      ->where('scd.analysis_id  = ?', $id);

		$data = $query->fetchOne();
		return $data;
	}

	/*
	*
	* This function saves the user image name.
	*
	*/
	public function saveCombineUserData($arr,$id) 
	{
		$rec = $this->searchPreviousRecord($id);
		if($arr['combined_author_names'])
		{ 
			if($rec)
			{
				$rec->combined_usernames = $arr['combined_author_names'];
				$rec->created_at = date('Y-m-d H:i:s');
				$rec->save();
			}
			else
			{
				$this->analysis_id = $id;
				$this->combined_usernames = $arr['combined_author_names'];
				$this->created_at = date('Y-m-d H:i:s');
				$this->save();
			}
		}
	}
	
	/*
	*
	* This function makes links fo user names.
	*
	*/
	public function searchRecordMakeLink($id) 
	{
		$profile = new SfGuardUserProfile();
		$query = Doctrine_Query::create()->from('SbtCombinedAnalysisData scd')->where('scd.analysis_id  = ?', $id);
		$data = $query->fetchOne();
		
		$str = '';
		
		if($data)
		{
			$arr = explode(',',$data->combined_usernames);
			
			for($i=0;$i<count($arr);$i++)
			{
				$id = $profile->getUserFromFullName($arr[$i]);
				
				if($i == 0)
				{
					if($id && $id > 0)	$str = '<a class="cursor main_link_color" href="http://'.$_SERVER["HTTP_HOST"].'/sbt/sbtMinProfile/id/'.$id.'">'.$arr[$i].'</a>';
					else  $str = $str.$arr[$i];
				}
				else
				{
					if($id && $id > 0)	$str = $str.',<a class="cursor main_link_color" href="http://'.$_SERVER["HTTP_HOST"].'/sbt/sbtMinProfile/id/'.$id.'">'.$arr[$i].'</a>';
					else $str = $str.$arr[$i];
				}
			}
		}
		return $str;
	}
}