<?php

/**
 * SbtFriendRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtFriendRequest extends BaseSbtFriendRequest
{
	/*
	*
	* Update record as per users reply to friend request.
	*
	*/
	
	public function update_reply_status($statusid,$rec_id) 
	{ 
		$update_cri = Doctrine_Query::create()
    				->update('SbtFriendRequest sfr')
       				->set('sfr.status', '?', $statusid)
					->set('sfr.updated_at', '?', date("Y-m-d H:i"))
       				->where('sfr.id = ?', $rec_id);

    	$updated = $update_cri->execute();
	}
}