<?php

/**
 * SbtMarketStocklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtMarketStocklist extends BaseSbtMarketStocklist
{
	/*
	*
	* This function fetches stocklist from market id.
	*
	*/
	public function fetchStockFromMarket($marketid) 
	{
		// For stocklist name
		$stock_list_cri = Doctrine_Query::create()
						->from('SbtMarketStocklist sms')
						->innerJoin('sms.SbtMarket sm')
						->innerJoin('sms.SbtStockList sl')
						->andWhere('sm.id = ?',$marketid);
			
		$stocklist_data = $stock_list_cri->execute();
		return $stocklist_data;
	} 
	
	/*
	*
	* This function fetches sectors from stocklist id.
	*
	*/
	public function fetchSectorFromMarket($stocklist_id) 
	{
		// For sector name
		$sector_list_cri = Doctrine_Query::create()
						->select('DISTINCT ss.sector_name AS sector_name,ss.id AS sector_id')
						->from('SbtStocklistSector sss')
						->innerJoin('sss.SbtSector ss')
						->innerJoin('sss.SbtStockList sl')
						->whereIn('sl.id',$stocklist_id)
						->setHydrationMode(Doctrine::HYDRATE_NONE);
		$sector_data = $sector_list_cri->execute();
		return $sector_data;
	} 
}