<?php

/**
 * SbtObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtObject extends BaseSbtObject
{
   /*
	*
	* This function return selected market record
	*
	*/
	public function getDataFromObject($typeid)
	{
		$query = Doctrine_Query::create()->from('SbtObject so');
		$query = $query->where('so.type_id = ?', $typeid);
		$data = $query->execute();
		return $data;
	}

   /*
	*
	* This function return selected objects
	*
	*/
	public function getObjectFromTypeStock($typeid,$stocklistid)
	{
		$query = Doctrine_Query::create()->from('SbtObject so')->where('so.type_id = ? AND so.stocklist_id = ?', array($typeid,$stocklistid));
		$data = $query->execute();
		return $data;
	}	
	
   /*
	*
	* This function return selected objects
	*
	*/
	public function getObjectFromTypeSector($typeid,$sectorid)
	{
	//echo $typeid.','.$sectorid; die;
		$query = Doctrine_Query::create()->from('SbtObject so')->where('so.type_id = ? AND so.sector_id = ?', array($typeid,$sectorid));
		$data = $query->execute();
		
		return $data;
	}	

   /*
	*
	* This function return selected objects
	*
	*/
	public function getObjectFromTypeStockSector($typeid,$stocklistid,$sectorid)
	{
		$query = Doctrine_Query::create()->from('SbtObject so')->where('so.type_id = ? AND so.stocklist_id = ? AND so.sector_id = ?', array($typeid,$stocklistid,$sectorid));
		
		$data = $query->execute();
		return $data;
	}
	
	public static function getCntSector($typeid,$stocklistid)
	{
		$query = Doctrine_Query::create()->select('count(so.id)')->from('SbtObject so')->where('so.type_id = ? AND so.stocklist_id = ? AND so.sector_id > 0', array($typeid,$stocklistid));
		
		$data = $query->fetchArray();
		
		return $data[0]['count'];
	}
}