<?php

/**
 * SbtRecentVisitor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtRecentVisitor extends BaseSbtRecentVisitor
{
   /*
	*
	* Updates the recent visited user to a profile.
	*
	*/
	
	public function updateRecentVisited($profile_user_id,$profile_visitor_id) 
	{ 
		$this->profile_user_id = $profile_user_id;
		$this->profile_visitor_id = $profile_visitor_id;
		$this->created_at = date("Y-m-d H:i:s");
		$this->save();
	}
	
   /*
	*
	* Finds all recently visited user to a profile.
	*
	*/
	public function findRecentVisitor($profile_user_id) 
	{ 
		$profile = new SfGuardUserProfile();
		$arr = $name_id_arr = array();
		
		$visited_user_cri = Doctrine_Query::create()
						  ->from('SbtRecentVisitor srv')
					      ->where('srv.profile_user_id = ?',$profile_user_id);
					
        $visited_data = $visited_user_cri->execute();
		
		foreach($visited_data as $data)
		{
			if(!in_array($data->profile_visitor_id, $arr)) 
			{
    			$arr[] = $data->profile_visitor_id;
				$str = $profile->getFullUserName($data->profile_visitor_id); 
				$name_id_arr[$data->profile_visitor_id] = $profile->getFullUserName($data->profile_visitor_id); 
			}
		}
		return $name_id_arr;
	}
	
}