<?php

/**
 * SbtUserBlogProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtUserBlogProfile extends BaseSbtUserBlogProfile
{
	/*
	*
	* This function searches for already existing image of user.
	*
	*/
	public function searchForPreviousRecord($user_id) 
	{
		$query = Doctrine_Query::create()
	   					      ->from('SbtUserBlogProfile sup')
						      ->where('sup.user_id  = ?', $user_id);

		$data = $query->fetchOne();
		return $data;
	}

	/*
	*
	* This function saves the user blog profile image name.
	*
	*/
	public function saveUserBlogProfileImage($user_id,$filename) 
	{
		$rec = $this->searchForPreviousRecord($user_id);
		if(!$rec)
		{ 
			$this->user_id = $user_id;
			$this->blog_header_image = $filename;
			$this->created_at = date('Y-m-d H:i:s');
			$this->save();
		}
		else
		{
			$rec->blog_header_image = $filename;
			$rec->created_at = date('Y-m-d H:i:s');
			$rec->save();
		}
	}
}