# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          #host:   83.253.6.204
          #port:   587
          #host:        213.180.95.199
          #host:       mail.borstjanaren.se
          host:       mail2.hallenborgsandstrom.se
          port:       587
          encryption: ~
          username:   noreply@hallenborgsandstrom.se
          password:   Kvtyw63945#
          #username:   matjare@thephpprojects.com
          #password:   Matjare456

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none
  
  transport:
    class: Swift_SmtpTransport
    param:
      host:       mail.borstjanaren.se
      #host:       mail.thephpprojects.com
      port:       587
      encryption: ~
      username:   ~
      password:   ~
      #username:   matjare@thephpprojects.com
      #password:   Matjare456

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          #host:        213.180.95.199   
          host:       mail.borstjanaren.se
          port:       587
          encryption: ~
          username:   ~
          password:   ~
          #username:   matjare@thephpprojects.com
          #password:   Matjare456
  user:
    class: myUser
    param:
      timeout: 43200