<?php

/**
 * ArticleTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleTemplate extends BaseArticleTemplate
{
	/*
	*
	* This function inserts new template record.
	*
	*/
	
	public function insertNewTemplateRecord($form,$arr) 
	{ 
		$this->article_date = date("Y-m-d H:i:s"); 
		$this->template_name = $arr['tplt_name']; 
		$this->author_id = $form->getValue('author_id');
		$this->category_id = $form->getValue('category_id');
		$this->type_id = $form->getValue('type_id');
		$this->object_id = $form->getValue('object_id');
		$this->title = $form->getValue('title');
		$this->image = $form->getValue('image');
		$this->image_text = $form->getValue('image_text');
		$this->text = $form->getValue('text');
		$this->author = $form->getValue('author');
		$this->art_statid = $form->getValue('art_statid');
		
		if($form->getValue('author'))	$this->author = $form->getValue('author');
		else	$this->author = $arr['author_name'];

		$this->save();
		return $this->template_id;
	}

}