<?php

/**
 * ArticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleCategory extends BaseArticleCategory
{
	/*
	*
	* This function returns selected article category.
	*
	*/
	
	public function getSelectedArticleCategory($index) 
	{ 
		$selected_article_category_cri = Doctrine_Query::create()
	   					      		   ->from('ArticleCategory ac')
						               ->where('ac.category_id = ?', $index);

		$selected_article_category_data = $selected_article_category_cri->fetchOne();
		return $selected_article_category_data;
	}
	
	/*
	*
	* This function saves article category name.
	*
	*/
	
	public function setArticleCategoryName($name)
	{ 
		$this->category_name = $name;
		$this->save();
	}
	
	/*
	*
	* This function addes new article category name.
	*
	*/
	
	public function addNewArticleCategoryName($name)
	{ 
		$this->category_name = $name;
		$this->save();
	}
	
	/*
	*
	* This function returns 1 find type exsist, else 0.
	*
	*/
	
	public function isCategoryPresent($category_name) 
	{ 
		$find_article_category_cri = Doctrine_Query::create()
	   					      	   ->from('ArticleCategory ac')
						           ->where('ac.category_name = ?', $category_name);

		$find_article_category_data = $find_article_category_cri->fetchOne();
		return $find_article_category_data ? 1 : 0;
	}
}