<?php

/**
 * BtchartFavorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtchartFavorite extends BaseBtchartFavorite
{
    public function addToFavorite($user_id,$stock_id, $stock_type, $chart_type, $desc) 
	{
        $new_rec = new BtchartFavorite();
        $new_rec->user_id = $user_id;
        $new_rec->stock_id = $stock_id;
        $new_rec->stock_type = $stock_type;
        $new_rec->chart_type = $chart_type;
        $new_rec->description = $desc;
        $new_rec->created_at = date("Y-m-d H:i:s");
        $new_rec->save();
	} 
    /**
	*
	* This function returns specified favorite lists for chart.
	*
	*/
	public function getSpecifiedFavorite($user_id,$column_id,$order) 
	{
            $query = Doctrine_Query::create()->from('BtchartFavorite btf')->where('btf.user_id = ?', array($user_id));
            if ($column_id) {
                switch ($column_id) {
                    case 'article': $query = $query->orderBy('btf.description ' . $order);
                        break;
                    case 'default': $query = $query->orderBy('btf.created_at DESC');
                        break;
                }
            }
            if (!$column_id)
                $query = $query->orderBy('btf.created_at DESC');
            return $query;
	}
   /**
	*
	* This function returns specified favorite record.
	*
	*/
	public function getSingleFavoriteRecord($id) 
	{ 
		$query = Doctrine_Query::create()->from('BtchartFavorite btf')->where('btf.id = ? ', $id);
		$data = $query->fetchOne();
		return $data;
	}        
    public function getFavoriteStatus($stock_id, $stock_type, $chart_type, $user_id)
    {
        $q = Doctrine_Query::create()
            ->from('BtchartFavorite btf')
            ->where('btf.user_id = ? ', $user_id)
            ->andWhere('btf.stock_id = ? ', $stock_id)
            ->andWhere('btf.stock_type = ? ', $stock_type)
            ->andWhere('btf.chart_type = ? ', $chart_type)
            ->execute();
        return count($q);
    }
}