<?php

/**
 * BtchartCompanyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtchartCompanyCategory extends BaseBtchartCompanyCategory
{
	public static function getCompanyCategory()
    {
		$q = Doctrine_Query::create()                          
	   					      ->from('BtchartCompanyCategory bcc')
                              ->execute();
        $cat_arr = array();
        foreach($q as $data){
            $cat_arr[$data->id] = $data->company_type;
        } 
        return $cat_arr;                                     
    } 
}