<?php

/**
 * BtforumCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtforumCategory extends BaseBtforumCategory
{
	public function __toString()
	{
		return $this->btforum_category_name;
	}
	
	public function getSubCategories($id)
	{
		$cat_arr =  array();
		$query = Doctrine_Query::create()
	   	       ->from('BtforumCategory bc')
			   ->where('bc.id = ?',$id);
		$id_data = $query->fetchOne();
		
		$sub_arr = explode(',',$id_data->btforum_subcategory_id_list);
		
		$subcat_name_query = Doctrine_Query::create()
	   	                   ->from('BtforumSubcategory bfsc')
			               ->whereIn('bfsc.id', $sub_arr);
		$name_data = $subcat_name_query->execute(); 				   
		
		foreach($name_data as $cat)
		{ 
			$cat_arr[$cat->id] = $cat->btforum_subcategory_name;
		}
		
        return $cat_arr;
	}
}