<?php

/**
 * BtNewsletterType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtNewsletterType extends BaseBtNewsletterType
{
   /**
	*
	* This function returns all record.
	*
	*/
	public function addNewNewsletter($name) 
	{ 
		$type = new BtNewsletterType();
		$type->newsletter_name = $name;
		$type->save();
	}

   /**
	*
	* This function returns all record.
	*
	*/
	public function getAllNewsletterType() 
	{ 
		$query = Doctrine_Query::create()->from('BtNewsletterType bnt');
		$data = $query->execute();
		return $data;
	}
	
  /**
	*
	* This function returns selected record.
	*
	*/
	public function getSelectedNewsletterType($id) 
	{ 
		$query = Doctrine_Query::create()->from('BtNewsletterType bnt')->where('bnt.id = ?',$id);
		$data = $query->fetchOne();
		return $data;
	}
	
  /**
	*
	* This function returns selected record from name.
	*
	*/
	public function isNewsletterPresent($name) 
	{ 
		$query = Doctrine_Query::create()->from('BtNewsletterType bnt')->where('bnt.newsletter_name = ?',$name);
		$data = $query->fetchOne();
		return $data ? 1 : 0;
	}
}