<?php

/**
 * BtShopArticleType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BtShopArticleType extends BaseBtShopArticleType
{
	public function __toString()
	{
		return $this->btshop_type_name;
	}
	
   /*
	*
	* This function fetches all article type.
	*
	*/
	public function fecthAllShopArticleType()
	{
		$arr = array();
		$query = Doctrine_Query::create()->from('BtShopArticleType bsat');
		$data =  $query->execute();
		
		foreach($data as $rec)
		{
			$arr[$rec->id] = $rec->btshop_type_name;
		}
		
		return $arr;
	}

   /*
	*
	* This function returns array of all btshop article types
	*
	*/    
    public function getAllShopArticleTypes()
    {
		$q = Doctrine_Query::create()
            ->select('bsat.id, bsat.btshop_type_name')
            ->from('BtShopArticleType bsat')
            ->execute();
        $article_type_arr = array();
        foreach ($q as $data)
        {
            $article_type_arr[$data->id] = $data->btshop_type_name;
        }
        return $article_type_arr;               
    }    
}