<?php

/**
 * Countries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Countries extends BaseCountries
{
   /**
	*
	* This function returns all countries.
	*
	*/
	public function getAllCountries() 
	{ 
		$query = Doctrine_Query::create()->from('Countries c')->orderBy('c.country_name');
		$data = $query->execute();
		return $data;
	}
	
   /**
	*
	* This function returns perticular record.
	*
	*/
	public function getOneRegionCode($iso_code) 
	{ 
		$query = Doctrine_Query::create()->from('Countries c')->where('c.iso_code = ? ', $iso_code);
		$data = $query->fetchOne();
		return $data ? $data->country_region_id : '';
	}
}