<?php

/**
 * CountryShipping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CountryShipping extends BaseCountryShipping
{
   /**
	*
	* This function returns price as per weight.
	*
	*/
	public function getShippingCostFromWeight($total_weight,$region_code)
	{ 
		if($total_weight > 0)
		{
			$query = Doctrine_Query::create()->from('CountryShipping cs')->where('cs.country_region_id = ? AND cs.item_weight >= ?', array($region_code,$total_weight));
			$query = $query->orderBy('cs.id ASC');
			$data = $query->fetchOne();
			return $data ? $data->price : 0;
		}
		else return 0;
	}
}