<?php

/**
 * NewsletterPublic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NewsletterPublic extends BaseNewsletterPublic
{
   /*
	*
	* To check weither user is a Newsletter Subcriber.
	*
	*/
	public function IsNewsletterSubcriber($email)
	{
		$find_public_cri = Doctrine_Query::create()
						   ->from('NewsletterPublic n')
						   ->where('n.email = ?', $email);
		$public_data = $find_public_cri->fetchOne();
		return $public_data;
	}

   /*
	*
	* To Subcribe the newsletter
	*
	*/
	public function addNewsletterSubcriber($email)
	{
		$this->email = $email;
		$this->save();
	}
	
   /*
	*
	* To get the rec count.
	*
	*/
	public function getNewsPublicCnt()
	{
		$qty = '';
		$query_str = "SELECT DISTINCT count(email) as qty FROM newsletter_public";
		$q = Doctrine_Manager::getInstance()->getCurrentConnection();
		$result = $q->execute($query_str);
		
		foreach($result as $rec)
		{
			$qty = $rec['qty'];
		}
		
		return $qty;
	}
	
   /*
	*
	* To get a perticular record from Newsletter Public.
	*
	*/
	public function getPerticularNewsPublicRecord($id)
	{
		$query = Doctrine_Query::create()->from('NewsletterPublic np')->where('np.id = ? ',$id);
		$data = $query->fetchOne();
		return $data; 
	}
	
   /*
	*
	* To search similar email addresses.
	*
	*/
	public function getSimilarEmailAddressesQuery($email)
	{
		$query = Doctrine_Query::create()->from('NewsletterPublic np');
		$query = $query->where('np.email LIKE ?', '%'.$email.'%');
		$query = $query->orderBy('np.id DESC');
        return $query;
	}
	
   /*
	*
	* To get all records.
	*
	*/
	public function getAllNewsPublicRecordQuery()
	{
		$query = Doctrine_Query::create()->from('NewsletterPublic np');
		$query = $query->orderBy('np.id DESC');
        return $query;
	}
	
   /*
	*
	* To search a perticular email address.
	*
	*/
	public function isNewsPublicEmailPresent($email)
	{
		$query = Doctrine_Query::create()->from('NewsletterPublic np');
		$query = $query->where('np.email LIKE ?', '%'.$email.'%');
        $data = $query->fetchOne();
		return $data; 
	}
        
        //code change by sandeep
        public function checkEmailInNewsletterPublic($email_id)
	{ 
		$query = Doctrine_Query::create()->from('NewsletterPublic na');
		$query = $query->where('na.email = ?', $email_id);
		$data = $query->fetchArray();
		return $data;
	}
        //code change by sandeep end
        
   /*
	*
	* To check weither user is a Newsletter Public Subcriber.
	*
	*/
	public function IsNewsletterPublic($email)
	{
		$find_public_cri = Doctrine_Query::create()
						   ->from('NewsletterPublic n')
						   ->where('n.email = ?', $email);
		$public_data = $find_public_cri->fetchOne();
		return $public_data;
	}
        
   /*
	*
	* To Subcribe the newsletter
	*
	*/
	public function addNewsletterPublic($email)
	{
		$this->email = $email;
		$this->save();
	}
	
}