<?php

/**
 * Objekt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Objekt extends BaseObjekt
{
	/*
	*
	* This function returns selected object.
	*
	*/
	
	public function getSelectedObject($index)
	{ 
		$selected_object_cri = Doctrine_Query::create()
	   					      ->from('Objekt obj')
						      ->where('obj.object_id = ?', $index);

		$selected_object_data = $selected_object_cri->fetchOne();
		return $selected_object_data;
	}
	
	/*
	*
	* This function saves object information.
	*
	*/
	
	public function setSelectedObject($name,$country)
	{ 
		$this->object_name = $name;
		$this->object_country = $country;
		$this->object_date = date("Y-m-d");
		$this->save();
		
		return $this->object_id;
	}
	
	/*
	*
	* This function returns 'Already Exsist' if object exsist else ''.
	*
	*/
	
	public function isObjectPresent($object_name,$object_country,$object_id)
	{  
		$query = Doctrine_Query::create()->from('Objekt obj');
		if($object_name) $query = $query->andWhere("obj.object_name LIKE '%".$object_name."%'");
		if($object_country) $query = $query->andWhere("obj.object_country LIKE '%".$object_country."%'");
			
		//echo $query->getSqlQuery();
		$data = $query->fetchOne();
		
		if($object_id)
		{
			if($data)
			{
				if($data->object_id == $object_id)	return 'update';
				else return 'present';
			}
			else return 'new';	 
		}
		else 
		{
			if($data)
			{
				if($data->object_id > 0)	return 'present';
			}
			else return 'new';
		}
	}
}