<?php

/**
 * SbtAnalysisComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtAnalysisComment extends BaseSbtAnalysisComment
{
	/*
	*
	* This function returns name of the user who has commented on a perticular article;
	*
	*/
	
	public function getCommentedUsername($user_id) 
	{ 
	 	$username_cri = Doctrine_Query::create()
	   					  ->from('SfGuardUserProfile sup')
						  ->where('sup.user_id = '.$user_id);
                                                  //->where('sup.user_id = '.$user_id.' and use_alias = 0');
		
		$username_data = $username_cri->fetchOne();


		if($username_data) 
		{
			$name = ($username_data->usernamealias) ? $username_data->usernamealias : $username_data->firstname.' '.$username_data->lastname;
			
			return $name;
		}	
		
		/*if(!$username_data)
		{
			$fetch_user_cri = Doctrine_Query::create()
							->from('SfGuardUserProfile sup')
							->where('sup.user_id = '.$user_id.' and use_alias = 1');
			$userdata = $fetch_user_cri->fetchOne();
			
			return $userdata ? $userdata->usernamealias : '';
		}*/
		
	}

	/*
	*
	* This function returns the comment data for a perticular record. 
	*
	*/
	
	public function getSelectedComment($id) 
	{ 
	 	$comment_data_cri = Doctrine_Query::create()
	   					  ->from('SbtAnalysisComment sac')
						  ->where('sac.id = ?', $id);
		
		$comment_data = $comment_data_cri->fetchOne();

        $desc[0]['analysis_comment'] = $comment_data->analysis_comment;
        $desc[1]['subject'] = $comment_data->subject;
        $str = $desc[0]['analysis_comment'].'_'.$desc[1]['subject'];
		return $str;
 	    
	}

	/*
	*
	* This function saves the edited comment.
	*
	*/
	
	public function getSaveComment($comment,$comment_subject) 
	{ 
	 	$this->analysis_comment = $comment;
        $this->subject = $comment_subject;
		$this->save();
	}
	
	/*
	*
	* This function returns total no. of comment to a perticular article.
	*
	*/
	
	public function getTotalCommentCount($id) 
	{ 
	 	$comment_data_cri = Doctrine_Query::create()
	   					  ->from('SbtAnalysisComment sac')
						  ->where('sac.analysis_id = ?', $id)
						  ->orderBy('sac.id DESC');
		
		$comment_data = $comment_data_cri->execute();

		$cnt = $comment_data ? count($comment_data) :  0;
		return $cnt;
		//foreach($comment_data as $data)	{	$cnt = $cnt + 1; }

	}
	
   /*
	*
	* This function deletes all the comments on a perticular analysis.
	*
	*/
	public function deleteAnalysisComments($analysis_id) 
	{ 
		$query = Doctrine_Query::create()
			   ->from('SbtAnalysisComment sac')
			   ->where('sac.analysis_id = ?',$analysis_id);
			   
		$data = $query->execute(); 
		
		foreach($data as $rec)
		{
			$rec->delete();
		}
	}
    public function delAnalysisCommentData($id){  
      
            $del_comment_query = Doctrine_Query::create()
                ->delete('SbtAnalysisComment sac')
                ->where('sac.id = ?',$id);

            $rows = $del_comment_query->execute();
            return $rows;    
            //echo $del_comment_query->getSqlQuery();
            
        }	
}