<?php

/**
 * SbtAnalysisSuggestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtAnalysisSuggestion extends BaseSbtAnalysisSuggestion
{
   /*
	*
	* This function returns a perticular analysis.
	*
	*/
	
	public function getSelectedSuggestion($index) 
	{ 
		$selected_article_cri = Doctrine_Query::create()
	   					      ->from('SbtAnalysisSuggestion sa')
						      ->where('sa.id = ?', $index);

		$selected_article_data = $selected_article_cri->fetchOne();
		return $selected_article_data;
	}
	
   /*
	*
	* This function returns a last suggestion of perticular analysis.
	*
	*/
	
	public function getLastSuggestion($index) 
	{ 
		$selected_article_cri = Doctrine_Query::create()
	   					      ->from('SbtAnalysisSuggestion sa')
						      ->where('sa.analysis_id = ?', $index)
							  ->orderBy('sa.id DESC');

		$selected_article_data = $selected_article_cri->fetchOne();
		return $selected_article_data;
	}
}