<?php

/**
 * SbtBlogVoteDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtBlogVoteDetails extends BaseSbtBlogVoteDetails
{
	/*
	*
	* This function addes new record in SbtBlogVoteDetails table.
	*
	*/
	
	public function addVoteDetails($type_id,$blog_id,$author_id,$user_id,$vote_type_id) 
	{ 
		$new_obj = new SbtVoteDetails();
		
		$new_obj->type_id = $type_id;
		$new_obj->author_id = $author_id;
		$new_obj->art_blog_id = $blog_id;
		$new_obj->user_id = $user_id;
		$new_obj->vote_type_id = $vote_type_id;
		$new_obj->created_at = date("Y-m-d H:i:s");
		$new_obj->save();
	}
	
	/*
	*
	* This function to find a perticular record.
	*
	*/
	
	public function findVoteDetails($type_id,$blog_id,$user_id) 
	{ 
		$find_blog_cri = Doctrine_Query::create()
	   					      ->from('SbtVoteDetails svd')
						      ->where('svd.type_id = ? AND svd.art_blog_id = ? AND svd.user_id = ?', array($type_id,$blog_id,$user_id));

		$one_bloge_data = $find_blog_cri->fetchOne();
		
		if($one_bloge_data)	return 1;
		else return 0;
	}
	
   /*
	*
	* This function finds the no. of stars to a perticular blog.
	*
	*/
	
	public function getStarForBlog($blog_id) 
	{ 
		$find_blog_cri = Doctrine_Query::create()
		                      ->select('svd.art_blog_id,svd.vote_type_id')
	   					      ->from('SbtVoteDetails svd')
						      ->where('svd.type_id = ? AND svd.art_blog_id = ?', array(2,$blog_id));
							  
		$data = $find_blog_cri->fetchArray();
		$type_of_star_cnt = 0;
		
		for($i=0; $i<count($data); $i++)
		{
			$type_of_star_cnt = $type_of_star_cnt + $data[$i]['vote_type_id'];
		}
		
		$no_of_stars = round($type_of_star_cnt / $i);
		return $no_of_stars;
	}
}