<?php

/**
 * SbtPublisherRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtPublisherRequest extends BaseSbtPublisherRequest
{

       public function isPublisher(){

            $guardUser = Doctrine::getTable('sfGuardUser')->find($this->author_id);

            $result = $guardUser->hasGroup('SbtArticlePublisher');

            return $result && $result == true  ? 1 : 0;

        }
}