<?php

/**
 * SbtStockList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtStockList extends BaseSbtStockList
{
   /*
	*
	* This function return selected stocklist record
	*
	*/
	public function getSelctedStockList($id_arr)
	{
		$arr = array();
		
		if(count($id_arr) > 0)
		{
			$q = Doctrine_Query::create()
			   ->from('SbtStockList ssl')
			   ->whereIn('ssl.id', $id_arr)
			   ->orderBy('ssl.display_order');
	
			$data = $q->execute();
			
			foreach($data as $rec)
			{
				$arr[$rec->id] = $rec->stock_name;
			}
		}
		return $arr;
	}
}