<?php

/**
 * SbtUserprofilePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SbtUserprofilePhoto extends BaseSbtUserprofilePhoto
{
	/*
	*
	* This function searches for already existing image of user.
	*
	*/
	public function searchForRecord($user_id) 
	{
		$query = Doctrine_Query::create()
	   					      ->from('SbtUserprofilePhoto sup')
						      ->where('sup.user_id  = ?', $user_id);

		$data = $query->fetchOne();
		return $data;
	}
	
	
	/*
	*
	* This function fecthes all record from table.
	*
	*/
	public function fetchAllPhotoRecord() 
	{
		$query = Doctrine_Query::create()
	   					      ->select('sup.user_id,sup.profile_photo_name')
							  ->from('SbtUserprofilePhoto sup');

		$data = $query->fetchArray();
		return $data;
	}


	/*
	*
	* This function saves the user image name.
	*
	*/
	public function saveUserProfileImage($user_id,$filename) 
	{
		$rec = $this->searchForRecord($user_id);
		if(!$rec)
		{ 
			$this->user_id = $user_id;
			$this->profile_photo_name = $filename;
			$this->created_at = date('Y-m-d H:i:s');
			$this->save();
		}
		else
		{
			$rec->profile_photo_name = $filename;
			$rec->created_at = date('Y-m-d H:i:s');
			$rec->save();
		}
	}
}