<?php

/**
 * UserTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserTransaction extends BaseUserTransaction
{
   /*
	*
	* This function fetches user transaction.
	*
	*/
	public function fetchTransaction($id) 
	{
		$fetch_user_transaction_cri = Doctrine_Query::create()->from('UserTransaction ut')->where('ut.user_id = ?', $id);
		$userdata = $fetch_user_transaction_cri->execute();
		
		return $userdata;
    }
	
   /*
	*
	* This function is user transaction.
	*
	*/
	public function saveUserTransaction($value,$pay_amount) 
	{
		$this->user_id = $value;
		$this->amount_added = $pay_amount;
		$this->transaction_date = date("Y-m-d H:i:s");
		$this->save();
	}
	
	/*
	*
	* This function is saves new user information.
	*
	*/
	public function userPayment($id) 
	{
		$calculate_payment_data = $this->fetchTransaction($id);
				
		$total_payment = 0;
		
		foreach($calculate_payment_data as $data)
		{
			$total_payment = $total_payment + $data->getAmountAdded();
		}
				
		return $total_payment; 		
	}
}