<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtShopPriceDetails', 'doctrine');

/**
 * BaseBtShopPriceDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $btshop_article_id
 * @property integer $btshop_product_quantity
 * @property integer $btshop_price_unit_id
 * @property integer $btshop_product_price
 * @property string $btshop_product_text
 * @property timestamp $created_at
 * @property BtShopArticle $BtShopArticle
 * 
 * @method integer            getId()                      Returns the current record's "id" value
 * @method integer            getBtshopArticleId()         Returns the current record's "btshop_article_id" value
 * @method integer            getBtshopProductQuantity()   Returns the current record's "btshop_product_quantity" value
 * @method integer            getBtshopPriceUnitId()       Returns the current record's "btshop_price_unit_id" value
 * @method integer            getBtshopProductPrice()      Returns the current record's "btshop_product_price" value
 * @method string             getBtshopProductText()       Returns the current record's "btshop_product_text" value
 * @method timestamp          getCreatedAt()               Returns the current record's "created_at" value
 * @method BtShopArticle      getBtShopArticle()           Returns the current record's "BtShopArticle" value
 * @method BtShopPriceDetails setId()                      Sets the current record's "id" value
 * @method BtShopPriceDetails setBtshopArticleId()         Sets the current record's "btshop_article_id" value
 * @method BtShopPriceDetails setBtshopProductQuantity()   Sets the current record's "btshop_product_quantity" value
 * @method BtShopPriceDetails setBtshopPriceUnitId()       Sets the current record's "btshop_price_unit_id" value
 * @method BtShopPriceDetails setBtshopProductPrice()      Sets the current record's "btshop_product_price" value
 * @method BtShopPriceDetails setBtshopProductText()       Sets the current record's "btshop_product_text" value
 * @method BtShopPriceDetails setCreatedAt()               Sets the current record's "created_at" value
 * @method BtShopPriceDetails setBtShopArticle()           Sets the current record's "BtShopArticle" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtShopPriceDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btshop_price_details');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('btshop_article_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btshop_product_quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btshop_price_unit_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btshop_product_price', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btshop_product_text', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BtShopArticle', array(
             'local' => 'btshop_article_id',
             'foreign' => 'id'));
    }
}