<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtShopArticleType', 'doctrine');

/**
 * BaseBtShopArticleType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $btshop_type_name
 * @property boolean $login_required
 * @property Doctrine_Collection $BtShopArticle
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getBtshopTypeName()   Returns the current record's "btshop_type_name" value
 * @method boolean             getLoginRequired()    Returns the current record's "login_required" value
 * @method Doctrine_Collection getBtShopArticle()    Returns the current record's "BtShopArticle" collection
 * @method BtShopArticleType   setId()               Sets the current record's "id" value
 * @method BtShopArticleType   setBtshopTypeName()   Sets the current record's "btshop_type_name" value
 * @method BtShopArticleType   setLoginRequired()    Sets the current record's "login_required" value
 * @method BtShopArticleType   setBtShopArticle()    Sets the current record's "BtShopArticle" collection
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtShopArticleType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btshop_article_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('btshop_type_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('login_required', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BtShopArticle', array(
             'local' => 'id',
             'foreign' => 'btshop_type_id'));
    }
}