<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtAnalysisMedalType', 'doctrine');

/**
 * BaseSbtAnalysisMedalType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $analysis_medal_name
 * 
 * @method integer              getId()                  Returns the current record's "id" value
 * @method string               getAnalysisMedalName()   Returns the current record's "analysis_medal_name" value
 * @method SbtAnalysisMedalType setId()                  Sets the current record's "id" value
 * @method SbtAnalysisMedalType setAnalysisMedalName()   Sets the current record's "analysis_medal_name" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtAnalysisMedalType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_analysis_medal_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('analysis_medal_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}