<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtVisits', 'doctrine');

/**
 * BaseSbtVisits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $visit_count
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getVisitCount()  Returns the current record's "visit_count" value
 * @method SbtVisits setId()          Sets the current record's "id" value
 * @method SbtVisits setVisitCount()  Sets the current record's "visit_count" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtVisits extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_visits');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('visit_count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}