<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtStocklistSector', 'doctrine');

/**
 * BaseSbtStocklistSector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sbt_stocklist_id
 * @property integer $sbt_sector_id
 * @property SbtSector $SbtSector
 * @property SbtStockList $SbtStockList
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method integer            getSbtStocklistId()   Returns the current record's "sbt_stocklist_id" value
 * @method integer            getSbtSectorId()      Returns the current record's "sbt_sector_id" value
 * @method SbtSector          getSbtSector()        Returns the current record's "SbtSector" value
 * @method SbtStockList       getSbtStockList()     Returns the current record's "SbtStockList" value
 * @method SbtStocklistSector setId()               Sets the current record's "id" value
 * @method SbtStocklistSector setSbtStocklistId()   Sets the current record's "sbt_stocklist_id" value
 * @method SbtStocklistSector setSbtSectorId()      Sets the current record's "sbt_sector_id" value
 * @method SbtStocklistSector setSbtSector()        Sets the current record's "SbtSector" value
 * @method SbtStocklistSector setSbtStockList()     Sets the current record's "SbtStockList" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtStocklistSector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_stocklist_sector');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sbt_stocklist_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sbt_sector_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SbtSector', array(
             'local' => 'sbt_sector_id',
             'foreign' => 'id'));

        $this->hasOne('SbtStockList', array(
             'local' => 'sbt_stocklist_id',
             'foreign' => 'id'));
    }
}