<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClassroomSubscribtion', 'doctrine');

/**
 * BaseClassroomSubscribtion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $group_id
 * @property integer $topic_id
 * @property integer $mail_subscribe
 * 
 * @method integer               getId()             Returns the current record's "id" value
 * @method integer               getUserId()         Returns the current record's "user_id" value
 * @method integer               getGroupId()        Returns the current record's "group_id" value
 * @method integer               getTopicId()        Returns the current record's "topic_id" value
 * @method integer               getMailSubscribe()  Returns the current record's "mail_subscribe" value
 * @method ClassroomSubscribtion setId()             Sets the current record's "id" value
 * @method ClassroomSubscribtion setUserId()         Sets the current record's "user_id" value
 * @method ClassroomSubscribtion setGroupId()        Sets the current record's "group_id" value
 * @method ClassroomSubscribtion setTopicId()        Sets the current record's "topic_id" value
 * @method ClassroomSubscribtion setMailSubscribe()  Sets the current record's "mail_subscribe" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassroomSubscribtion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classroom_subscribtion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('topic_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mail_subscribe', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}