<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NewsletterSent', 'doctrine');

/**
 * BaseNewsletterSent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property integer $recipiants
 * @property integer $kundgrupp
 * @property string $subject
 * @property string $body
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method date           getDate()       Returns the current record's "date" value
 * @method integer        getRecipiants() Returns the current record's "recipiants" value
 * @method integer        getKundgrupp()  Returns the current record's "kundgrupp" value
 * @method string         getSubject()    Returns the current record's "subject" value
 * @method string         getBody()       Returns the current record's "body" value
 * @method NewsletterSent setId()         Sets the current record's "id" value
 * @method NewsletterSent setDate()       Sets the current record's "date" value
 * @method NewsletterSent setRecipiants() Sets the current record's "recipiants" value
 * @method NewsletterSent setKundgrupp()  Sets the current record's "kundgrupp" value
 * @method NewsletterSent setSubject()    Sets the current record's "subject" value
 * @method NewsletterSent setBody()       Sets the current record's "body" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletterSent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_sent');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('recipiants', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('kundgrupp', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('subject', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('body', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}