<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtNewsletterType', 'doctrine');

/**
 * BaseBtNewsletterType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $newsletter_name
 * 
 * @method integer          getId()              Returns the current record's "id" value
 * @method string           getNewsletterName()  Returns the current record's "newsletter_name" value
 * @method BtNewsletterType setId()              Sets the current record's "id" value
 * @method BtNewsletterType setNewsletterName()  Sets the current record's "newsletter_name" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtNewsletterType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bt_newsletter_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('newsletter_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}