<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subscription', 'doctrine');

/**
 * BaseSubscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $purchase_id
 * @property integer $product_id
 * @property integer $product_type_id
 * @property integer $btchart_type_id
 * @property integer $articleornot
 * @property integer $subscription_duration
 * @property string $subscription_duration_unit
 * @property string $scheme_name
 * @property date $start_date
 * @property date $end_date
 * @property timestamp $created_at
 * @property Purchase $Purchase
 * @property BtShopArticle $BtShopArticle
 * 
 * @method integer       getId()                         Returns the current record's "id" value
 * @method integer       getPurchaseId()                 Returns the current record's "purchase_id" value
 * @method integer       getProductId()                  Returns the current record's "product_id" value
 * @method integer       getProductTypeId()              Returns the current record's "product_type_id" value
 * @method integer       getBtchartTypeId()              Returns the current record's "btchart_type_id" value
 * @method integer       getArticleornot()               Returns the current record's "articleornot" value
 * @method integer       getSubscriptionDuration()       Returns the current record's "subscription_duration" value
 * @method string        getSubscriptionDurationUnit()   Returns the current record's "subscription_duration_unit" value
 * @method string        getSchemeName()                 Returns the current record's "scheme_name" value
 * @method date          getStartDate()                  Returns the current record's "start_date" value
 * @method date          getEndDate()                    Returns the current record's "end_date" value
 * @method timestamp     getCreatedAt()                  Returns the current record's "created_at" value
 * @method Purchase      getPurchase()                   Returns the current record's "Purchase" value
 * @method BtShopArticle getBtShopArticle()              Returns the current record's "BtShopArticle" value
 * @method Subscription  setId()                         Sets the current record's "id" value
 * @method Subscription  setPurchaseId()                 Sets the current record's "purchase_id" value
 * @method Subscription  setProductId()                  Sets the current record's "product_id" value
 * @method Subscription  setProductTypeId()              Sets the current record's "product_type_id" value
 * @method Subscription  setBtchartTypeId()              Sets the current record's "btchart_type_id" value
 * @method Subscription  setArticleornot()               Sets the current record's "articleornot" value
 * @method Subscription  setSubscriptionDuration()       Sets the current record's "subscription_duration" value
 * @method Subscription  setSubscriptionDurationUnit()   Sets the current record's "subscription_duration_unit" value
 * @method Subscription  setSchemeName()                 Sets the current record's "scheme_name" value
 * @method Subscription  setStartDate()                  Sets the current record's "start_date" value
 * @method Subscription  setEndDate()                    Sets the current record's "end_date" value
 * @method Subscription  setCreatedAt()                  Sets the current record's "created_at" value
 * @method Subscription  setPurchase()                   Sets the current record's "Purchase" value
 * @method Subscription  setBtShopArticle()              Sets the current record's "BtShopArticle" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubscription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscription');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('purchase_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btchart_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('articleornot', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subscription_duration', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subscription_duration_unit', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('scheme_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Purchase', array(
             'local' => 'purchase_id',
             'foreign' => 'id'));

        $this->hasOne('BtShopArticle', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}