<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtRecentVisitor', 'doctrine');

/**
 * BaseSbtRecentVisitor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profile_user_id
 * @property integer $profile_visitor_id
 * @property timestamp $created_at
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method integer          getProfileUserId()      Returns the current record's "profile_user_id" value
 * @method integer          getProfileVisitorId()   Returns the current record's "profile_visitor_id" value
 * @method timestamp        getCreatedAt()          Returns the current record's "created_at" value
 * @method SbtRecentVisitor setId()                 Sets the current record's "id" value
 * @method SbtRecentVisitor setProfileUserId()      Sets the current record's "profile_user_id" value
 * @method SbtRecentVisitor setProfileVisitorId()   Sets the current record's "profile_visitor_id" value
 * @method SbtRecentVisitor setCreatedAt()          Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtRecentVisitor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_recent_visitor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('profile_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('profile_visitor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}