<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserTransaction', 'doctrine');

/**
 * BaseUserTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $amount_added
 * @property timestamp $transaction_date
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer         getId()               Returns the current record's "id" value
 * @method integer         getUserId()           Returns the current record's "user_id" value
 * @method integer         getAmountAdded()      Returns the current record's "amount_added" value
 * @method timestamp       getTransactionDate()  Returns the current record's "transaction_date" value
 * @method sfGuardUser     getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method UserTransaction setId()               Sets the current record's "id" value
 * @method UserTransaction setUserId()           Sets the current record's "user_id" value
 * @method UserTransaction setAmountAdded()      Sets the current record's "amount_added" value
 * @method UserTransaction setTransactionDate()  Sets the current record's "transaction_date" value
 * @method UserTransaction setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_transaction');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('amount_added', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('transaction_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}