<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArticleHtml', 'doctrine');

/**
 * BaseArticleHtml
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $article_id
 * @property string $html_file_path
 * @property timestamp $created_at
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getArticleId()      Returns the current record's "article_id" value
 * @method string      getHtmlFilePath()   Returns the current record's "html_file_path" value
 * @method timestamp   getCreatedAt()      Returns the current record's "created_at" value
 * @method ArticleHtml setId()             Sets the current record's "id" value
 * @method ArticleHtml setArticleId()      Sets the current record's "article_id" value
 * @method ArticleHtml setHtmlFilePath()   Sets the current record's "html_file_path" value
 * @method ArticleHtml setCreatedAt()      Sets the current record's "created_at" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleHtml extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_html');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('article_id', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('html_file_path', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}