<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtShopPriceQtyUnit', 'doctrine');

/**
 * BaseBtShopPriceQtyUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $btshop_price_unit
 * 
 * @method integer            getId()                Returns the current record's "id" value
 * @method string             getBtshopPriceUnit()   Returns the current record's "btshop_price_unit" value
 * @method BtShopPriceQtyUnit setId()                Sets the current record's "id" value
 * @method BtShopPriceQtyUnit setBtshopPriceUnit()   Sets the current record's "btshop_price_unit" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtShopPriceQtyUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btshop_price_qty_unit');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('btshop_price_unit', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}