<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BtShopArticle', 'doctrine');

/**
 * BaseBtShopArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $btshop_article_author_id
 * @property integer $btshop_type_id
 * @property integer $btchart_type_id
 * @property string $btshop_article_title
 * @property string $btshop_article_subtitle
 * @property string $btshop_product_image
 * @property string $btshop_product_intro_text
 * @property string $btshop_product_description
 * @property float $product_weight
 * @property integer $published
 * @property boolean $is_downloadable
 * @property boolean $is_sellable
 * @property string $download_url
 * @property timestamp $created_at
 * @property BtShopArticleType $BtShopArticleType
 * @property Doctrine_Collection $BtShopPriceDetails
 * @property Doctrine_Collection $Subscription
 * @property Doctrine_Collection $Article
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method integer             getBtshopArticleAuthorId()      Returns the current record's "btshop_article_author_id" value
 * @method integer             getBtshopTypeId()               Returns the current record's "btshop_type_id" value
 * @method integer             getBtchartTypeId()              Returns the current record's "btchart_type_id" value
 * @method string              getBtshopArticleTitle()         Returns the current record's "btshop_article_title" value
 * @method string              getBtshopArticleSubtitle()      Returns the current record's "btshop_article_subtitle" value
 * @method string              getBtshopProductImage()         Returns the current record's "btshop_product_image" value
 * @method string              getBtshopProductIntroText()     Returns the current record's "btshop_product_intro_text" value
 * @method string              getBtshopProductDescription()   Returns the current record's "btshop_product_description" value
 * @method float               getProductWeight()              Returns the current record's "product_weight" value
 * @method integer             getPublished()                  Returns the current record's "published" value
 * @method boolean             getIsDownloadable()             Returns the current record's "is_downloadable" value
 * @method boolean             getIsSellable()                 Returns the current record's "is_sellable" value
 * @method string              getDownloadUrl()                Returns the current record's "download_url" value
 * @method timestamp           getCreatedAt()                  Returns the current record's "created_at" value
 * @method BtShopArticleType   getBtShopArticleType()          Returns the current record's "BtShopArticleType" value
 * @method Doctrine_Collection getBtShopPriceDetails()         Returns the current record's "BtShopPriceDetails" collection
 * @method Doctrine_Collection getSubscription()               Returns the current record's "Subscription" collection
 * @method Doctrine_Collection getArticle()                    Returns the current record's "Article" collection
 * @method BtShopArticle       setId()                         Sets the current record's "id" value
 * @method BtShopArticle       setBtshopArticleAuthorId()      Sets the current record's "btshop_article_author_id" value
 * @method BtShopArticle       setBtshopTypeId()               Sets the current record's "btshop_type_id" value
 * @method BtShopArticle       setBtchartTypeId()              Sets the current record's "btchart_type_id" value
 * @method BtShopArticle       setBtshopArticleTitle()         Sets the current record's "btshop_article_title" value
 * @method BtShopArticle       setBtshopArticleSubtitle()      Sets the current record's "btshop_article_subtitle" value
 * @method BtShopArticle       setBtshopProductImage()         Sets the current record's "btshop_product_image" value
 * @method BtShopArticle       setBtshopProductIntroText()     Sets the current record's "btshop_product_intro_text" value
 * @method BtShopArticle       setBtshopProductDescription()   Sets the current record's "btshop_product_description" value
 * @method BtShopArticle       setProductWeight()              Sets the current record's "product_weight" value
 * @method BtShopArticle       setPublished()                  Sets the current record's "published" value
 * @method BtShopArticle       setIsDownloadable()             Sets the current record's "is_downloadable" value
 * @method BtShopArticle       setIsSellable()                 Sets the current record's "is_sellable" value
 * @method BtShopArticle       setDownloadUrl()                Sets the current record's "download_url" value
 * @method BtShopArticle       setCreatedAt()                  Sets the current record's "created_at" value
 * @method BtShopArticle       setBtShopArticleType()          Sets the current record's "BtShopArticleType" value
 * @method BtShopArticle       setBtShopPriceDetails()         Sets the current record's "BtShopPriceDetails" collection
 * @method BtShopArticle       setSubscription()               Sets the current record's "Subscription" collection
 * @method BtShopArticle       setArticle()                    Sets the current record's "Article" collection
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBtShopArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('btshop_article');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('btshop_article_author_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('btshop_type_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('btchart_type_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('btshop_article_title', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('btshop_article_subtitle', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('btshop_product_image', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('btshop_product_intro_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('btshop_product_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('product_weight', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('published', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('is_downloadable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_sellable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('download_url', 'string', 200, array(
             'type' => 'string',
             'default' => '',
             'length' => 200,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BtShopArticleType', array(
             'local' => 'btshop_type_id',
             'foreign' => 'id'));

        $this->hasMany('BtShopPriceDetails', array(
             'local' => 'id',
             'foreign' => 'btshop_article_id'));

        $this->hasMany('Subscription', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Article', array(
             'local' => 'id',
             'foreign' => 'btshop_id'));
    }
}