<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SbtSector', 'doctrine');

/**
 * BaseSbtSector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $sector_name
 * @property Doctrine_Collection $SbtStocklistSector
 * @property Doctrine_Collection $SbtObject
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getSectorName()         Returns the current record's "sector_name" value
 * @method Doctrine_Collection getSbtStocklistSector() Returns the current record's "SbtStocklistSector" collection
 * @method Doctrine_Collection getSbtObject()          Returns the current record's "SbtObject" collection
 * @method SbtSector           setId()                 Sets the current record's "id" value
 * @method SbtSector           setSectorName()         Sets the current record's "sector_name" value
 * @method SbtSector           setSbtStocklistSector() Sets the current record's "SbtStocklistSector" collection
 * @method SbtSector           setSbtObject()          Sets the current record's "SbtObject" collection
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSbtSector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sbt_sector');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sector_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SbtStocklistSector', array(
             'local' => 'id',
             'foreign' => 'sbt_sector_id'));

        $this->hasMany('SbtObject', array(
             'local' => 'id',
             'foreign' => 'sector_id'));
    }
}