<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArticleCount', 'doctrine');

/**
 * BaseArticleCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $art_id
 * @property integer $click_cnt
 * @property Article $Article
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getArtId()     Returns the current record's "art_id" value
 * @method integer      getClickCnt()  Returns the current record's "click_cnt" value
 * @method Article      getArticle()   Returns the current record's "Article" value
 * @method ArticleCount setId()        Sets the current record's "id" value
 * @method ArticleCount setArtId()     Sets the current record's "art_id" value
 * @method ArticleCount setClickCnt()  Sets the current record's "click_cnt" value
 * @method ArticleCount setArticle()   Sets the current record's "Article" value
 * 
 * @package    sisterbt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_count');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('art_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('click_cnt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'art_id',
             'foreign' => 'article_id'));
    }
}