<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/08/30 14:57:01
sfConfig::add(array(
  'app_system_culture' => 'en,es',
  'app_mail_sender_email' => 'systerbt@borstjanaren.se',
  'app_mail_reply_email' => 'systerbt@borstjanaren.se',
  'app_mail_shop_email' => 'btshop@borstjanaren.se',
  'app_host_name' => 'www.borstjanaren.se',
  'app_newsletter_email' => 'ej_svarsadress@borstjanaren.se',
));
