<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/08/30 14:57:07
$this->security = array (
  'createarticle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'addArticle',
      ),
    ),
  ),
  'articlelist' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'listArticle',
      ),
    ),
  ),
  'articleproperties' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'articleProperties',
      ),
    ),
  ),
  'listobject' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'listObject',
      ),
    ),
  ),
  'editobject' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'editObject',
      ),
    ),
  ),
  'sendarticleupdateform' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'super_admin',
    ),
  ),
  'btingressimageupload' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'addArticle',
      ),
    ),
  ),
  'btdetailimageupload' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'addArticle',
      ),
    ),
  ),
  'getsearcharticlelist' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_admin',
        1 => 'listArticle',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'super_admin',
    ),
  ),
);
