<?php
// auto-generated by sfViewConfigHandler
// date: 2019/08/30 14:57:08
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addHttpMeta('Expires', '-1', false);
  $response->addHttpMeta('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', false);
  $response->addHttpMeta('Pragma', 'no-cache', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main_back.css', '', array ());
  $response->addStylesheet('custom-theme/jquery-ui-1.8.2.custom.css', '', array ());
  $response->addStylesheet('/sfFormExtraPlugin/css/jquery.autocompleter.css', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('common_back.js', '', array ());
  $response->addJavascript('newsletter.js', '', array ());
  $response->addJavascript('tinymce/js/tinymce/tinymce.min.js', '', array ());
  $response->addJavascript('jquery.dimensions.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.2.custom.min.js', '', array ());
  $response->addJavascript('/sfFormExtraPlugin/js/jquery.autocompleter.js', '', array ());
  $response->addJavascript('jquery.history.js', '', array ());


